name: Validate translations

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      
    - name: Setup Node.js environment
      uses: actions/setup-node@v4
      with:
        node-version: '22'
    
    - name: Run script
      run: node admin/validate_translation.js
