name: Validate Tranlation File for Localization

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.2
      with:
        node-version: '10.x'
    
    - name: Run script
      run: node admin/validate_translation.js
